%
% bib.inc - Bibliography
%
% Written 1999-2002 by Werner Almesberger
% Copyright 1999-2001 EPFL-ICA
% Copyright 2001,2002 Bivio Networks, Network Robots
%

\bibitem{ALM99}Almesberger, Werner; Hadi Salim, Jamal; Kuznetsov, Alexey.
  {\em Differentiated Services on Linux} (work in progress),
  Internet Draft \url{draft-almesberger-wajhak-diffserv-linux-01.txt},
  June 1999.
  \url{ftp://icaftp.epfl.ch/pub/linux/diffserv/misc/dsid-01.txt.gz}
\bibitem{LARTC}Hubert, Bert; et al.
  {\em Linux Advanced Routing \& Traffic Control},
  \url{http://lartc.org/}
\bibitem{KR88}Kernighan, Brian W.; Ritchie, Dennis M.
  {\em The C programming language},
  Prentice Hall, 1988.
\bibitem{RFC768}Postel, Jon.
  {\em User Datagram Protocol},
  IETF, August 1980.
\bibitem{RFC791}Postel, Jon.
  {\em Internet Protocol},
  IETF, September 1981.
\bibitem{RFC792}Postel, Jon.
  {\em Internet Control Message Protocol},
  IETF, September 1981.
\bibitem{RFC793}Postel, Jon.
  {\em Transmission Control Protocol},
  IETF, September 1981.
\bibitem{RFC1349}Almquist, Philip.
  {\em Type of Service in the Internet Protocol Suite},
  IETF, July 1992.
\bibitem{RFC1858}Ziemba, G. Paul; Reed, Darren; Traina, Paul.
  {\em Security Considerations for IP Fragment Filtering},
  IETF, October 1995.
\bibitem{RFC2236}Fenner, William C.
  {\em Internet Group Management Protocol, Version 2},
  IETF, November 1997.
\bibitem{RFC2373}Hinden, Robert M.; Deering, Stephen E.
  {\em IP Version 6 Addressing Architecture},
  IETF, July 1998.
\bibitem{RFC2402}Kent, Stephen; Atkinson, Randall.
  {\em IP Authentication Header},
  IETF, November 1998.
\bibitem{RFC2406}Kent, Stephen; Atkinson, Randall.
  {\em IP Encapsulating Security Payload (ESP)},
  IETF, November 1998.
\bibitem{RFC2460}Deering, Stephen E.; Hinden, Robert M.
  {\em Internet Protocol, Version 6 (IPv6) Specification},
  IETF, December 1998.
\bibitem{RFC2474}Nichols, Kathleen; Blake, Steven; Baker, Fred;
  Black, David L.
  {\em Definition of the Differentiated Services Field (DS Field)
  in the IPv4 and IPv6 Headers},
  IETF, December 1998.
\bibitem{RFC2475}Blake, Steven; Black, David; Carlson, Mark;
  Davies, Elwyn; Wang, Zheng; Weiss, Walter.
  {\em An Architecture for Differentiated Services},
  IETF, December 1998.
\bibitem{RFC2697}Heinanen, Juha; Guerin, Roch.
  {\em A Single Rate Three Color Marker},
  IETF, September 1999.
\bibitem{RFC2698}Heinanen, Juha; Guerin, Roch.
  {\em A Two Rate Three Color Marker},
  IETF, September 1999.
\bibitem{RFC3128}Miller, Ian.
  {\em Protection Against a Variant of the Tiny Fragment Attack},
  IETF, June 2001.
\bibitem{RFC3168}Ramakrishnan, K. K.; Floyd, Sally; Black, David L.
  {\em The Addition of Explicit Congestion Notification (ECN) to IP},
  IETF, September 2001.
