#!/bin/sh
#
# tcc-ext-null - Blackhole configuration
#
# Written 2002 by Werner Almesberger
# Copyright 2002 Network Robots
#

if [ -z "$1" ]; then
    echo "usage: $0 mode ..." 1>&2
    exit 1
fi

mode=$1
shift
case "$mode" in
    config)	for n in debug_target "$@"; do
		    echo "$n"
		done;;
    check)	;;
    build)	;;
    *)		echo "$0: unrecognized mode $mode" 1>&2
		exit 1;;
esac
exit 0
